Update marquee.php
dikisiswanto/OpenSID-Cosmos pull request #57
Opened 2020-06-09 15:16 UTC by will2469

memperbaiki eror 404 saat klik link artikel di teks berjalan

2020-06-09 15:37 UTC, will2469 commented
![photo_2020-06-09_22-36-25](https://user-images.githubusercontent.com/17868552/84168524-b4eb5680-aaa1-11ea-894e-064ecfee0606.jpg)

memperbaiki untuk permasalahan yang saya alami diatas

2020-06-09 21:14 UTC, dikisiswanto requested changes

2020-06-09 21:14 UTC, dikisiswanto commented on partials/marquee.php
> +					/* memperbaiki code untul link artikel site.url/artikel/site.url/artikel/to/an/artikel
Kode yang sudah tidak digunakan sebaiknya dihapus saja. Agar filenya tetap rapi. Terima kasih.

2020-06-09 21:15 UTC, dikisiswanto commented
Mohon lihat komentar 🙂

2020-06-10 00:53 UTC, will2469 commented
done

2020-06-10 01:15 UTC, merged

2020-06-10 01:15 UTC, dikisiswanto commented
Terima kasih @will2469. Sudah digabung ke `master`

2020-06-10 17:29 UTC, will2469 commented
sama-sama, senang dapat bekerjasama